server:
  port: 8082 #端口号

eureka:
  client:
    serviceUrl: #注册中心的注册地址
      defaultZone: http://127.0.0.1:8081/eureka/

spring:
  application:
    name: XinMusic-Feign #服务名称--调用的时候根据名称来调用该服务的方法
  main:
    allow-bean-definition-overriding: true  #允许相同的名称覆盖

#feign:
#  httpclient:
#    connection-timeout: 5000
#  hystrix:
#    enabled: false
