server:
  port: 8083

eureka:
  client:
    serviceUrl: #注册中心的注册地址
      defaultZone: http://127.0.0.1:8081/eureka/
    #registerWithEureka: true
    #fetchRegistry: true #change to true，ok ok Last：Thanks
    #enabled: true
#  instance:
#    prefer-ip-address: true # 开启以端口ip的形式注册，方便线上找到服务
#    instance-id: 49.232.14.91:8083 # 线上地址

spring:
  application:
    name: xinmusic-comments
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xinmusic?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: admin
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10  #<--限制最大连接
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

mybatis:
  mapper-locations: classpath:com/ego14t/comments/mapper/xml/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: classpath:com/ego14t/comments/pojo/  # 注意：对应实体类的路径


logging:
  level:
    com.ego14t.comments.mapper: debug

workid:
  user: 0
  music: 1
  musiclist: 2
  comments: 3