server:
  port: 8091 #端口号

eureka:
  client:
    serviceUrl: #注册中心的注册地址
      defaultZone: http://127.0.0.1:8081/eureka/
  instance:
    prefer-ip-address: true # 开启以端口ip的形式注册，方便线上找到服务
    hostname: localhost

spring:
  application:
    name: XinMusic-Gateway #服务名称--调用的时候根据名称来调用该服务的方法

  cloud.gateway.routes:
    - id: music-resource
      uri: lb://XinMusic-Feign/
      predicates:
        - Path=/music/**

    - id: musiclist-resource
      uri: lb://XinMusic-Feign/
      predicates:
        - Path=/musiclist/**

    - id: music-comments
      uri: lb://XinMusic-Feign/
      predicates:
        - Path=/comments/**

    - id: music-user
      uri: lb://XinMusic-Feign/
      predicates:
        - Path=/users/**

    - id: music-oauth
      uri: lb://XinMusic-Oauth/
      predicates:
        - Path=/oauth/**

  #security.oauth2.resourceserver.jwt.jwk-set-uri: 'http://localhost:9000/.well-known/jwks.json'

