server:
  port: 8082 #端口号

eureka:
  client:
    serviceUrl: #注册中心的注册地址
      defaultZone: http://127.0.0.1:8081/eureka/
    #registerWithEureka: true
    #fetchRegistry: true #change to true，ok ok Last：Thanks
    #enabled: true
  #instance:
  #  prefer-ip-address: true # 开启以端口ip的形式注册，方便线上找到服务
  #  instance-id: 49.232.14.91:8083 # 线上地址
spring:
  application:
      name: music-list-service #服务名称--调用的时候根据名称来调用该服务的方法
  datasource:
    name: xinmusic #数据库名称
    type: com.alibaba.druid.pool.DruidDataSource
    #druid相关配置
    druid:
      #监控统计拦截的filters
      filters: stat
      driver-class-name: com.mysql.cj.jdbc.Driver
      #基本属性
      url: jdbc:mysql://127.0.0.1/xinmusic?characterEncoding=utf-8&serverTimezone=GMT%2B8
      username: root
      password: admin
      #配置初始化大小/最小/最大
      initial-size: 1
      min-idle: 1
      max-active: 20
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:com/ego14t/xinmusic/mapper/xml/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: classpath:com/ego14t/xinmusic/pojo/  # 注意：对应实体类的路径

#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  returnPageInfo: check

logging:
  level:
    com.ego14t.xinmusic.mapper: debug

